### ISSUE TITLE
Userdata support

### ISSUE THREAD

**Issue by kschamplin19** [Foo-Bear/bearserver#5]
Expand the authentication system to allow for user data to be stored. Some form of ID is needed to allow the database to find the user. Maybe Google Auth, to get email address. See readme for info on theorized data structure.

- [x]  Implement data structure
- [x] Make API calls
- [ ] Create secure authentication schema (and maybe integrate into current scheduling)
- [ ] Integrate into Redis (perhaps on a new db?)
- [ ] Utilize in applications

**Comment by kincaidoneil** [comment]
How about just localStorage? Most people only use their laptop, and don't
need their data synced across devices. Just an idea.

**Comment by kschamplin19** [comment]
Fair point. How persistent is localStorage?

**Comment by kincaidoneil** [comment]
Local storage persists indefinitely, unless the user clears cookies
(Firefox) or clears cache (Chrome), depending upon the implementation. It
can store up to 10MB per domain, or something like that.

**Comment by kschamplin19** [comment]
But what about those people on IE6? :stuck_out_tongue: 

I will look into it more, it would sure make life a lot easier for me.
